better handle remote files by avoiding full reads
natcap/geometamaker pull request #39
Opened 2024-09-11 17:55 UTC by davemfish

2024-09-17 21:05 UTC, phargogh requested changes
Thanks @davemfish !  I just had a couple very minor comments and suggestions for your consideration, but overall this looks great.

2024-09-17 21:05 UTC, phargogh commented on tests/test_geometamaker.py
> +        filepath = 'https://storage.googleapis.com/natcap-data-cache/global/aster-v3-1s/aster-v3-1s.tif'
I think this is a pretty reasonable thing to do, but, as you say, it expands the number of ways that the tests can fail that have nothing to do with the code in this repo.

Setting up a local HTTP server would be a good solution, and I could see another alternative being to use `mock` as well to simulate the return value of a simple file.

But for where we are in this project, I think the approach you have here would be just fine.

2024-09-24 13:15 UTC, davemfish commented on src/geometamaker/geometamaker.py
> +    if 'http' in scheme:
Yes, that's better!

2024-09-24 13:32 UTC, davemfish commented on src/geometamaker/geometamaker.py
> +    of = fsspec.open(source_dataset_path)
This is definitely a question I have asked myself too! Elsewhere before a call to `fsspec.open` I have this comment: `# Despite naming, this does not open a file that must be closed`, which I *think* is true, but it's confusing. `of.close()` is a  method, but I don't think it does anything unless `of.open()` was called, which I'm pretty sure it is not. `of` is an `OpenFile` instance: https://filesystem-spec.readthedocs.io/en/latest/_modules/fsspec/core.html#OpenFile

And here are some examples: https://filesystem-spec.readthedocs.io/en/latest/developer.html

Basically, we're using `fsspec.open` as a convenient way to access the filesystem (`of.fs`) and we're not actually opening the file itself. That's how I understand it anyway

2024-09-24 17:57 UTC, davemfish commented on src/geometamaker/geometamaker.py
> +    # files opened from http do not have mtime
Thanks for the suggestion, I dropped the use of `fsspec` in this instance as I do think it's worth getting the modified time.

2024-09-24 17:58 UTC, davemfish commented on tests/test_geometamaker.py
> +        filepath = 'https://storage.googleapis.com/natcap-data-cache/global/aster-v3-1s/aster-v3-1s.tif'
Alright I'm going to leave it as-is for now. Thanks for setting up that `natcap-data-cache`! It feels like a place we can depend on for a while.

2024-09-25 21:28 UTC, phargogh approved these changes
Looks great to me, thanks @davemfish !

2024-09-25 21:28 UTC, merged